# Generated by Django 5.1 on 2026-06-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='公告标题')),
                ('url', models.URLField(max_length=500, verbose_name='公告链接')),
                ('publish_date', models.DateField(blank=True, null=True, verbose_name='发布日期')),
                ('notice_type', models.CharField(choices=[('admission', '招生简章'), ('score_line', '复试分数线'), ('retest', '复试通知'), ('adjustment', '调剂公告'), ('admit_list', '拟录取名单'), ('other', '其他')], default='other', max_length=20, verbose_name='公告类型')),
                ('content_summary', models.TextField(blank=True, verbose_name='内容摘要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='采集时间')),
                ('college', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='schools.college', verbose_name='所属学院')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='schools.school', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '公告',
                'verbose_name_plural': '公告',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
