# Generated by Django 5.1 on 2026-06-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, verbose_name='专业代码')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('degree_type', models.CharField(choices=[('academic', '学术学位'), ('professional', '专业学位')], default='academic', max_length=20, verbose_name='学位类型')),
                ('research_direction', models.TextField(blank=True, verbose_name='研究方向')),
                ('exam_subjects', models.TextField(blank=True, help_text='初试科目，逗号分隔', verbose_name='考试科目')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='schools.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['college', 'code'],
                'unique_together': {('college', 'code', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('exam_subject', models.CharField(blank=True, max_length=100, verbose_name='对应考试科目')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_books', to='majors.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '参考书目',
                'verbose_name_plural': '参考书目',
                'ordering': ['major', 'book_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('plan_total', models.IntegerField(blank=True, null=True, verbose_name='计划招生总数')),
                ('plan_exam', models.IntegerField(blank=True, null=True, verbose_name='统考招生数')),
                ('plan_recommend', models.IntegerField(blank=True, null=True, verbose_name='推免招生数')),
                ('actual_total', models.IntegerField(blank=True, null=True, verbose_name='实际录取总数')),
                ('apply_count', models.IntegerField(blank=True, null=True, verbose_name='报名人数')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='majors.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '招生计划',
                'verbose_name_plural': '招生计划',
                'ordering': ['-year', 'major'],
                'unique_together': {('major', 'year')},
            },
        ),
        migrations.CreateModel(
            name='ScoreLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('total_score', models.IntegerField(verbose_name='总分线')),
                ('politics', models.IntegerField(blank=True, null=True, verbose_name='政治线')),
                ('english', models.IntegerField(blank=True, null=True, verbose_name='英语线')),
                ('math', models.IntegerField(blank=True, null=True, verbose_name='数学线')),
                ('professional', models.IntegerField(blank=True, null=True, verbose_name='专业课线')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_lines', to='majors.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '复试分数线',
                'verbose_name_plural': '复试分数线',
                'ordering': ['-year', 'major'],
                'unique_together': {('major', 'year')},
            },
        ),
    ]
