# Generated by Django 5.1 on 2026-06-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Major',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='如 081200、085404', max_length=10, verbose_name='专业代码')),
                ('name', models.CharField(max_length=100, verbose_name='专业名称')),
                ('degree_type', models.CharField(choices=[('academic', '学术学位'), ('professional', '专业学位')], default='academic', max_length=20, verbose_name='学位类型')),
                ('learning_type', models.CharField(choices=[('full_time', '全日制'), ('part_time', '非全日制'), ('both', '全日制+非全日制')], default='full_time', max_length=20, verbose_name='学习方式')),
                ('exam_type', models.CharField(blank=True, choices=[('unified', '统考'), ('single', '单考'), ('joint', '联考'), ('management', '管理类联考'), ('recommend', '推免'), ('other', '其他')], default='unified', max_length=20, verbose_name='考试类型')),
                ('doctoral_point', models.CharField(blank=True, choices=[('doctoral_first', '一级学科博士点'), ('doctoral_second', '二级学科博士点'), ('doctoral', '博士点'), ('master', '硕士点'), ('none', '无')], max_length=20, verbose_name='学位点情况')),
                ('platform_id', models.IntegerField(blank=True, db_index=True, help_text='对应平台 spe_id', null=True, verbose_name='采集平台专业ID')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='majors', to='schools.college', verbose_name='所属学院')),
                ('subject_category', models.ForeignKey(blank=True, help_text='关联到一级学科或专业学位类别', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='majors', to='subjects.subjectcategory', verbose_name='所属学科')),
            ],
            options={
                'verbose_name': '专业',
                'verbose_name_plural': '专业',
                'ordering': ['college', 'code'],
                'unique_together': {('college', 'code', 'name', 'learning_type')},
            },
        ),
        migrations.CreateModel(
            name='ReferenceBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, db_index=True, help_text='参考书目适用的考试年份', null=True, verbose_name='适用年份')),
                ('book_name', models.CharField(max_length=200, verbose_name='书名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('publisher', models.CharField(blank=True, max_length=100, verbose_name='出版社')),
                ('edition', models.CharField(blank=True, max_length=50, verbose_name='版本')),
                ('exam_subject', models.CharField(blank=True, max_length=100, verbose_name='对应考试科目')),
                ('raw_text', models.TextField(blank=True, help_text='接口返回的整段书目原文，用于兜底展示', verbose_name='原始书目文本')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reference_books', to='majors.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '参考书目',
                'verbose_name_plural': '参考书目',
                'ordering': ['major', '-year', 'book_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年份')),
                ('plan_total', models.IntegerField(blank=True, null=True, verbose_name='计划招生总数')),
                ('plan_exam', models.IntegerField(blank=True, null=True, verbose_name='统考计划数')),
                ('plan_recommend', models.IntegerField(blank=True, null=True, verbose_name='推免计划数')),
                ('actual_total', models.IntegerField(blank=True, null=True, verbose_name='实际录取总数')),
                ('actual_exam', models.IntegerField(blank=True, null=True, verbose_name='实际统考录取')),
                ('actual_recommend', models.IntegerField(blank=True, null=True, verbose_name='实际推免录取')),
                ('apply_count', models.IntegerField(blank=True, null=True, verbose_name='报名人数')),
                ('enroll_ratio', models.FloatField(blank=True, help_text='例如 8.5 表示 8.5:1', null=True, verbose_name='报录比')),
                ('avg_score', models.FloatField(blank=True, null=True, verbose_name='录取平均分')),
                ('min_score', models.IntegerField(blank=True, null=True, verbose_name='录取最低分')),
                ('max_score', models.IntegerField(blank=True, null=True, verbose_name='录取最高分')),
                ('plan_id', models.IntegerField(blank=True, db_index=True, help_text='对应平台 plan_id，按年份变化', null=True, verbose_name='平台计划ID')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='majors.major', verbose_name='专业')),
            ],
            options={
                'verbose_name': '招生计划',
                'verbose_name_plural': '招生计划',
                'ordering': ['-year', 'major'],
                'unique_together': {('major', 'year')},
            },
        ),
        migrations.CreateModel(
            name='NationalScoreLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('area', models.CharField(choices=[('A', 'A区'), ('B', 'B区')], max_length=2, verbose_name='区域')),
                ('total_score', models.IntegerField(verbose_name='总分线')),
                ('politics_score', models.IntegerField(blank=True, null=True, verbose_name='政治')),
                ('english_score', models.IntegerField(blank=True, null=True, verbose_name='英语')),
                ('subject_one_score', models.IntegerField(blank=True, null=True, verbose_name='业务课一')),
                ('subject_two_score', models.IntegerField(blank=True, null=True, verbose_name='业务课二')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('subject_category', models.ForeignKey(help_text='应关联到门类层级（如01哲学、08工学）', on_delete=django.db.models.deletion.CASCADE, related_name='national_score_lines', to='subjects.subjectcategory', verbose_name='学科门类')),
            ],
            options={
                'verbose_name': '国家线',
                'verbose_name_plural': '国家线',
                'ordering': ['-year', 'area', 'subject_category'],
                'unique_together': {('year', 'area', 'subject_category')},
            },
        ),
        migrations.CreateModel(
            name='ResearchDirection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('direction_code', models.CharField(blank=True, help_text='如 01、02', max_length=10, verbose_name='方向代码')),
                ('direction_name', models.CharField(help_text='清洗后的方向名', max_length=200, verbose_name='方向名称')),
                ('raw_text', models.CharField(blank=True, help_text='接口返回的原始字符串', max_length=300, verbose_name='原始文本')),
                ('recruit_number', models.IntegerField(blank=True, null=True, verbose_name='招生人数')),
                ('is_direction_based', models.BooleanField(default=False, help_text='True=招生人数是该方向独立的；False=招生人数是专业总数', verbose_name='是否按方向独立统计')),
                ('exam_subjects', models.TextField(blank=True, help_text='保留原文本格式', verbose_name='初试考试科目')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('major', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_directions', to='majors.major', verbose_name='所属专业')),
            ],
            options={
                'verbose_name': '研究方向',
                'verbose_name_plural': '研究方向',
                'ordering': ['major', '-year', 'direction_code'],
                'unique_together': {('major', 'year', 'direction_name')},
            },
        ),
        migrations.CreateModel(
            name='ScoreLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_type', models.CharField(choices=[('subject', '学科线'), ('major', '专业线')], db_index=True, max_length=20, verbose_name='分数线类型')),
                ('year', models.IntegerField(db_index=True, verbose_name='年份')),
                ('total_score', models.IntegerField(verbose_name='总分线')),
                ('politics_score', models.IntegerField(blank=True, null=True, verbose_name='政治')),
                ('english_score', models.IntegerField(blank=True, null=True, verbose_name='英语')),
                ('subject_one_score', models.IntegerField(blank=True, help_text='可能是数学、管综、专业基础等', null=True, verbose_name='业务课一分数')),
                ('subject_one_name', models.CharField(blank=True, help_text='如：数学一、199管综、临床综合', max_length=50, verbose_name='业务课一科目')),
                ('subject_two_score', models.IntegerField(blank=True, help_text='为空表示不考', null=True, verbose_name='业务课二分数')),
                ('subject_two_name', models.CharField(blank=True, max_length=50, verbose_name='业务课二科目')),
                ('diff_total', models.IntegerField(blank=True, help_text='正数表示高于国家线，负数表示低于', null=True, verbose_name='总分高于国家线')),
                ('diff_politics', models.IntegerField(blank=True, null=True, verbose_name='政治差值')),
                ('diff_english', models.IntegerField(blank=True, null=True, verbose_name='英语差值')),
                ('diff_subject_one', models.IntegerField(blank=True, null=True, verbose_name='业务课一差值')),
                ('diff_subject_two', models.IntegerField(blank=True, null=True, verbose_name='业务课二差值')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('major', models.ForeignKey(blank=True, help_text='专业线时填', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score_lines', to='majors.major', verbose_name='关联专业')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_lines', to='schools.school', verbose_name='所属学校')),
                ('subject_category', models.ForeignKey(blank=True, help_text='学科线时填', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='score_lines', to='subjects.subjectcategory', verbose_name='关联学科')),
            ],
            options={
                'verbose_name': '分数线',
                'verbose_name_plural': '分数线',
                'ordering': ['-year', 'school', 'score_type'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('score_type', 'subject')), fields=('school', 'subject_category', 'year'), name='unique_subject_score_line'), models.UniqueConstraint(condition=models.Q(('score_type', 'major')), fields=('school', 'major', 'year'), name='unique_major_score_line')],
            },
        ),
    ]
