# Generated by Django 5.1 on 2026-06-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('title', models.CharField(choices=[('professor', '教授'), ('associate', '副教授'), ('lecturer', '讲师'), ('assistant', '助理教授'), ('other', '其他')], default='other', max_length=20, verbose_name='职称')),
                ('research_area', models.TextField(blank=True, verbose_name='研究方向')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('homepage', models.URLField(blank=True, verbose_name='个人主页')),
                ('is_doctoral_supervisor', models.BooleanField(default=False, verbose_name='是否博导')),
                ('bio', models.TextField(blank=True, verbose_name='简介')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='schools.college', verbose_name='所属学院')),
            ],
            options={
                'verbose_name': '导师',
                'verbose_name_plural': '导师',
                'ordering': ['college', 'name'],
            },
        ),
    ]
