# Generated by Django 5.1 on 2026-06-23 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=10, unique=True, verbose_name='学科代码')),
                ('name', models.CharField(max_length=100, verbose_name='学科名称')),
                ('category', models.CharField(blank=True, help_text='如：工学、理学、文学等', max_length=50, verbose_name='学科门类')),
                ('level', models.CharField(choices=[('first', '一级学科'), ('second', '二级学科'), ('professional', '专业学位类别')], default='first', max_length=20, verbose_name='层级')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='subjects.subjectcategory', verbose_name='上级学科')),
            ],
            options={
                'verbose_name': '学科目录',
                'verbose_name_plural': '学科目录',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='评级')),
                ('evaluation_round', models.CharField(choices=[('round_4', '第四轮学科评估'), ('round_5', '第五轮学科评估')], max_length=20, verbose_name='评估轮次')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='评估年份')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_ratings', to='schools.school', verbose_name='所属学校')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subjects.subjectcategory', verbose_name='学科')),
            ],
            options={
                'verbose_name': '学科评级',
                'verbose_name_plural': '学科评级',
                'ordering': ['subject', '-evaluation_round', 'rating'],
                'unique_together': {('school', 'subject', 'evaluation_round')},
            },
        ),
    ]
