# Generated by Django 5.1 on 2026-06-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='2位=门类，4位=一级学科/专业类别，6位=二级学科/专业领域', max_length=10, unique=True, verbose_name='学科代码')),
                ('name', models.CharField(max_length=100, verbose_name='学科名称')),
                ('level', models.CharField(choices=[('category', '学科门类'), ('first_class', '一级学科'), ('second_class', '二级学科'), ('professional_category', '专业学位类别'), ('professional_field', '专业学位领域')], max_length=30, verbose_name='层级')),
                ('category_code', models.CharField(blank=True, db_index=True, help_text='所属学科门类代码，如 08', max_length=2, verbose_name='门类代码')),
                ('category_name', models.CharField(blank=True, help_text='所属学科门类名称，如 工学', max_length=50, verbose_name='门类名称')),
                ('is_academic', models.BooleanField(default=True, help_text='True=学术学位 False=专业学位', verbose_name='是否学硕')),
                ('is_self_set', models.BooleanField(default=False, help_text='代码带Z/J/S后缀的为自设', verbose_name='是否自设学科')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='subjects.subjectcategory', verbose_name='上级学科')),
            ],
            options={
                'verbose_name': '学科目录',
                'verbose_name_plural': '学科目录',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SubjectRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.CharField(choices=[('A+', 'A+'), ('A', 'A'), ('A-', 'A-'), ('B+', 'B+'), ('B', 'B'), ('B-', 'B-'), ('C+', 'C+'), ('C', 'C'), ('C-', 'C-')], max_length=5, verbose_name='评级')),
                ('evaluation_round', models.CharField(choices=[('round_4', '第四轮学科评估'), ('round_5', '第五轮学科评估')], max_length=20, verbose_name='评估轮次')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='评估年份')),
                ('source_url', models.URLField(blank=True, verbose_name='数据来源')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_ratings', to='schools.school', verbose_name='所属学校')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='subjects.subjectcategory', verbose_name='学科')),
            ],
            options={
                'verbose_name': '学科评级',
                'verbose_name_plural': '学科评级',
                'ordering': ['subject', '-evaluation_round', 'rating'],
                'unique_together': {('school', 'subject', 'evaluation_round')},
            },
        ),
    ]
