# Generated by Django 5.1 on 2026-06-24 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='省份名称')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='简称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
                ('code', models.CharField(blank=True, help_text='国标代码，如 10003', max_length=10, null=True, unique=True, verbose_name='学校代码')),
                ('level', models.CharField(choices=[('985', '985工程'), ('211', '211工程'), ('double_first', '双一流'), ('normal', '普通院校')], default='normal', max_length=20, verbose_name='院校层次')),
                ('is_985', models.BooleanField(default=False, verbose_name='是否985')),
                ('is_211', models.BooleanField(default=False, verbose_name='是否211')),
                ('is_double_first', models.BooleanField(default=False, verbose_name='是否双一流')),
                ('platform_id', models.IntegerField(blank=True, db_index=True, help_text='数据采集源的内部ID，仅用于增量更新和数据校验', null=True, verbose_name='采集平台ID')),
                ('province_area', models.CharField(blank=True, choices=[('A', 'A区'), ('B', 'B区')], help_text='国家线A区/B区', max_length=2, verbose_name='考研区域')),
                ('is_self_scoring', models.BooleanField(default=False, help_text='34所自主划线高校之一', verbose_name='是否自划线')),
                ('school_type', models.CharField(blank=True, choices=[('comprehensive', '综合类'), ('science_eng', '理工类'), ('normal_edu', '师范类'), ('medical', '医药类'), ('finance', '财经类'), ('political_law', '政法类'), ('agriculture', '农林类'), ('ethnic', '民族类'), ('art', '艺术类'), ('military', '军事类'), ('language', '语言类'), ('sports', '体育类'), ('other', '其他')], help_text='综合/理工/师范等分类', max_length=20, verbose_name='学校类型')),
                ('official_url', models.URLField(blank=True, verbose_name='研究生院官网')),
                ('logo_url', models.URLField(blank=True, verbose_name='校徽URL')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.province', verbose_name='所在省份')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='学院代码')),
                ('url', models.URLField(blank=True, verbose_name='学院官网')),
                ('platform_id', models.IntegerField(blank=True, db_index=True, help_text='对应平台 depart_id', null=True, verbose_name='采集平台ID')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='schools.school', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
