# Generated by Django 5.1 on 2026-06-22 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='省份名称')),
                ('short_name', models.CharField(blank=True, max_length=10, verbose_name='简称')),
            ],
            options={
                'verbose_name': '省份',
                'verbose_name_plural': '省份',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='学校名称')),
                ('code', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='学校代码')),
                ('level', models.CharField(choices=[('985', '985工程'), ('211', '211工程'), ('double_first', '双一流'), ('normal', '普通院校')], default='normal', max_length=20, verbose_name='院校层次')),
                ('is_985', models.BooleanField(default=False, verbose_name='是否985')),
                ('is_211', models.BooleanField(default=False, verbose_name='是否211')),
                ('is_double_first', models.BooleanField(default=False, verbose_name='是否双一流')),
                ('official_url', models.URLField(blank=True, verbose_name='研究生院官网')),
                ('logo_url', models.URLField(blank=True, verbose_name='校徽URL')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='schools.province', verbose_name='所在省份')),
            ],
            options={
                'verbose_name': '院校',
                'verbose_name_plural': '院校',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学院名称')),
                ('code', models.CharField(blank=True, max_length=10, verbose_name='学院代码')),
                ('url', models.URLField(blank=True, verbose_name='学院官网')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colleges', to='schools.school', verbose_name='所属学校')),
            ],
            options={
                'verbose_name': '学院',
                'verbose_name_plural': '学院',
                'ordering': ['school', 'name'],
                'unique_together': {('school', 'name')},
            },
        ),
    ]
